name: Build

on:

  workflow_dispatch:

    push:

    branches:

    - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - uses: actions/setup-java@v3

      with:

        distribution: temurin

        java-version: 11

        cache: gradle

    - run: |
    
        mkdir test_build

        chmod +x ./gradlew

        ./gradlew assembleRelease
    - run: |
        cd test_build
    - uses: actions/upload-artifact@v3

      with:

        name: auroraesp

        path: test_build
